export const Icons = {
    box: "📦",
    search: "🔍",
    user: "👤",
    settings: "⚙️",
    home: "🏠",
    message: "💬",
    calendar: "📅",
    star: "⭐",
    check: "✅",
    warning: "⚠️",
    info: "ℹ️",
    lock: "🔒",
    unlock: "🔓",
    edit: "✏️",
    delete: "🗑️",
    add: "➕",
    remove: "➖",
    email: "✉️",
    phone: "📞",
    location: "📍",
    filter: "🧐",
  };